### ISSUE TITLE
Strawhat Snowman NX Gachapon 

### ISSUE THREAD

**Issue by lightryuzaki** [lightryuzaki/ProjectNano4#13]
Straw hat snowman NX GACHAPON
-Issue: WZ Disconnet on second chat window
-the bug affects all players wanting to use armor nx gachapon 
- 5 priority 
- second chat window should display nx items available correctly and not disconnect (issue related to missing item in character.wz either client or server sided)
- nx gachapon exchanges 10mil meso for new nx item. 
- WHO: NPC strawhat snowman in @goto home map.

Potential fixes: Fix missing wz's or Remove the images from loading in the script.

**Comment by lightryuzaki** [comment]
Good first issue tag as we can just remove the item thats not in the files from displaying

**Comment by Evol93** [comment]
Can we just pull the old whole cash item and dump them into the new one?
