### ISSUE TITLE
NPC Thorr(ID 1301000) Should be a shop

### ISSUE THREAD

**Issue by lightryuzaki** [lightryuzaki/ProjectNano4#16]
https://cdn.discordapp.com/attachments/557421550903492608/561462351443001344/unknown.png

NPC should have potions for sale -SQL shop missing

1 priority ..

**Comment by lightryuzaki** [comment]
NPC should sell basic potions as well as arrows and subi throwing stars

**Comment by jknguyen22** [comment]
Found the issue. SQL DB did not have entries for this NPC ID. Work has been done.

Inserted the data into the table under the proper NPC ID. 

Should show up after server restart. Needs validation before closing Issue.

**Comment by jknguyen22** [comment]
Validated. Server is now showing items in shop for NPC ID# 1301000.
