### ISSUE TITLE
Replace CPQ NPC Text Portuguese Localization with English Localization

### ISSUE THREAD

**Issue by lightryuzaki** [lightryuzaki/ProjectNano4#17]
CPQ text in NPC Spiegelmann needs to be translated to english or pulled from HeavenMS github commit `https://github.com/ronancpl/HeavenMS/commit/83266508af2bce7ed466b1cac860b41b5cb32f0c` 

**EDIT 4/13/19** 
**New Task:** Remove all the Portuguese localization from the codebase and replace existing with English localization.

**Decision:** We will not support other localizations other than English.

**Comment by Evol93** [comment]
Will look into this

**Comment by Evol93** [comment]
Done

**Comment by minimucho1** [comment]
**New Task:** Remove all the Portuguese localization from the codebase and replace existing with English localization.

**Decision:** We will not support other localizations other than English.

**Comment by minimucho1** [comment]
This Issue is now waiting for prod server to be rebuilt and deployed before making necessary DB changes to close this Issue.

**Comment by minimucho1** [comment]
`lingua` has been removed from the `accounts` table. Issue is resolved. Closing.
