### ISSUE TITLE
Pendant of Spirit displays EXP but is not giving EXP to player

### ISSUE THREAD

**Issue by jknguyen22** [lightryuzaki/ProjectNano4#52]

**Comment by jknguyen22** [comment]
GOAL Example:
- base exp: 1000 (100%)
- party bonus: 1000 * (10% + 50%*6) = 3100
- pendant of spirit: 1000 * (30%) = 300

Contribution of PoS: 300 / (1000+3100) = 7.32% more exp when worn

**Comment by lightryuzaki** [comment]
**Expected:**
EXP Gain display Example-
Kill a blue snail 32 exp + pendant exp 3 = 35 exp gain total(35 is not displayed)
Monster Exp in White Line (32 EXP)
Pendant Exp in Yellow (3 EXP)

**Actual:**
Exp gain display example -
35exp + pendant exp 3 = 35 exp gain total 
Monster Exp in White Line (35 EXP)

This leads to players thinking they get 38 exp when in actuality they get 35 exp

**Comment by Evol93** [comment]
A blue snails give you 32 exp + 3 from the pendant. On the right side of the screen. It display 35 (White) exp and 3 (Yellow) exp from equip. Thus, people think that its 35 exp (from the snail) + 3 exp (from the pendant) which should be giving them 38 exp in total.
But in reality, the pendant exp is already added to the (white) amount

**Comment by minimucho1** [comment]
Pendant EXP Display is fixed. Closing.
