### ISSUE TITLE
Chalkboard (7 days) disappears after one use.

### ISSUE THREAD

**Issue by Evol93** [lightryuzaki/ProjectNano4#56]
**Whats happening:** If you purchase the chalkboard (7 days) from the cash shop. The item will be consume when you use it once.

**Whats it should be doing:** It should stay in the the inventory until the 7 days period is up and then expires.

**Comment by Evol93** [comment]
Jay wants to make it permanent.

**Comment by minimucho1** [comment]
Did this get fixed?

**Comment by Evol93** [comment]
Yes
