### ISSUE TITLE
Party Exp Gain is not functioning HUGE BUG

### ISSUE THREAD

**Issue by lightryuzaki** [lightryuzaki/ProjectNano4#6]
Party EXP Gain is not functioning what so ever. 
Expected behavior: when a player parties with another player and kills a monster the killer gets EXP for the mob (white text exp) and then the party members get a portion of the killers exp (yellow text exp) 
Current behavior: Players joining parties only receive yellow exp for mobs that kill and do not recieve white exp for any mobs they kill and exp is not shared with the party. 
Priority: 1
recreate the issue: join a party and kill a mob and the other character will recieve none of the exp

**Comment by Evol93** [comment]
change  
`attacker.gainExp(_personalExp, _partyExp, true, false, false);`
to
`attacker.gainExp(_personalExp, _partyExp, true, false, true);`

and
`public static final float PARTY_BONUS_EXP_RATE = 1;     `
to
`public static final float PARTY_BONUS_EXP_RATE = 1f;    ` 

Also add 

`giveExpToCharacter(MapleCharacter attacker, Float personalExp, Float partyExp, boolean white)`

**Comment by minimucho1** [comment]
Closing this and opening new issues
